var date = new Date();
console.log(date);
var year = date.getFullYear();
console.log(year);
var month = date.getMonth();
console.log(month);
var day =date.getDay();
console.log(day);
var currenthour = date.getHours();
console.log(currenthour);
var currentMinutes = date.getMinutes();
console.log(currentMinutes);